### PR TITLE
Update to changes in codal circuit playground

### PR DESCRIPTION
**Pull request by sabas1080**
Hi

this pullrequest updates to the changes of codal circuit playground

Thanks

### CODE REVIEW

**Comment by jamesadevine** [comment]
Thanks @sabas1080

**Comment by sabas1080** [comment]
@jamesadevine thanks, you can generate a snapshot please

**Comment by jamesadevine** [comment]
I’m more than happy to transfer this repository to you (or your org) if you’d like?

James.

On 19 Oct 2018, at 18:34, Sabas <notifications@github.com<mailto:notifications@github.com>> wrote:


@jamesadevine<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjamesadevine&data=02%7C01%7Cj.devine%40lancaster.ac.uk%7C230924575fd44bdc9d7c08d635e92fa6%7C9c9bcd11977a4e9ca9a0bc734090164a%7C1%7C0%7C636755672978251819&sdata=xQGJriHG6AiQbuSr3rtA6oKUe2ci4r85uy85IXYBGs4%3D&reserved=0> thanks, you can generate a snapshot please

**Comment by sabas1080** [comment]
Ok, seem right :D

**Comment by jamesadevine** [comment]
@sabas1080 I've initiated a transfer to your github.

**Pull request merged**
